import { createUseStyles } from "react-jss";

const style = {
  margin: 0,
  padding: 0,
  border: 0,
  verticalAlign: "baseline",
};

const useStyles = createUseStyles({
  "@global": {
    html: style,
    body: {
      ...style,
      lineHeight: "1",
    },
    div: style,
    span: style,
    applet: style,
    object: style,
    iframe: style,
    h1: style,
    h2: style,
    h3: style,
    h4: style,
    h5: style,
    h6: style,
    p: style,
    blockquote: {
      ...style,
      quotes: "none",
    },
    pre: style,
    a: style,
    abbr: style,
    acronym: style,
    address: style,
    big: style,
    cite: style,
    code: style,
    del: style,
    dfn: style,
    em: style,
    img: style,
    ins: style,
    kbd: style,
    q: {
      ...style,
      quotes: "none",
    },
    s: style,
    samp: style,
    small: style,
    strike: style,
    strong: style,
    sub: style,
    sup: style,
    tt: style,
    var: style,
    b: style,
    u: style,
    i: style,
    center: style,
    dl: style,
    dd: style,
    ol: {
      ...style,
      listStyle: "none",
    },
    ul: {
      ...style,
      listStyle: "none",
    },
    li: style,
    fieldset: style,
    form: style,
    label: style,
    legend: style,
    table: {
      ...style,
      borderCollapse: "collapse",
      borderSpacing: "0",
    },
    caption: style,
    tbody: style,
    tfoot: style,
    thead: style,
    tr: style,
    th: style,
    td: style,
    article: {
      ...style,
      display: "block",
    },
    aside: {
      ...style,
      display: "block",
    },
    canvas: style,
    details: {
      ...style,
      display: "block",
    },
    embed: style,
    figure: {
      ...style,
      display: "block",
    },
    figcaption: {
      ...style,
      display: "block",
    },
    footer: {
      ...style,
      display: "block",
    },
    header: {
      ...style,
      display: "block",
    },
    hgroup: {
      ...style,
      display: "block",
    },
    menu: {
      ...style,
      display: "block",
    },
    nav: {
      ...style,
      display: "block",
    },
    output: style,
    ruby: style,
    section: {
      ...style,
      display: "block",
    },
    summary: style,
    time: style,
    mark: style,
    audio: style,
    video: style,
  },
});

export default useStyles;
